import { quickAction } from './quickAction';
import { test, expect, type Page } from '@playwright/test';
const state = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem('planit-items-v4')!));
const calendar = (page: Page) => page.getByRole('region', { name: 'Weekly schedule' });
async function voice(page: Page) {
  await quickAction(page, 'Speak a change');
  await expect(page.getByRole('heading', { name: 'Here’s what I understood' })).toBeVisible();
}
test.beforeEach(async ({ page }) => { page.on('pageerror', error => { throw error; }); await page.clock.setFixedTime(new Date('2026-09-14T16:00:00Z')); await page.goto('/'); await page.getByRole('button', { name: 'Explore Demo', exact: true }).click(); await page.getByRole('button', { name: 'Expand context sidebar' }).click(); });

test('settings update range, 24-hour mode, timezone dates and persist after reload', async ({ page }) => {
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('tab', { name: 'Calendar', exact: true }).click();
  const settings = page.getByRole('complementary', { name: 'Calendar settings' });
  await expect(settings.getByLabel('Calendar visible start time')).toHaveValue('6');
  await expect(settings.getByLabel('Calendar visible end time')).toHaveValue('24');
  await settings.getByLabel('Calendar visible start time').selectOption('8');
  await settings.getByLabel('Calendar visible end time').selectOption('25');
  await expect(calendar(page).locator('.time-axis span').first()).toHaveText('8:00 AM');
  await expect(calendar(page).locator('.time-axis span').last()).toHaveText('1:00 AM +1d');
  await settings.getByLabel('Time format', { exact: true }).selectOption('24');
  await expect(calendar(page).locator('.time-axis span').first()).toHaveText('08:00');
  await settings.getByRole('switch').check();
  await expect(calendar(page).locator('.time-axis span').first()).toHaveText('00:00');
  await expect(calendar(page).locator('.time-axis span').last()).toHaveText('24:00');
  await expect(settings.getByLabel('Calendar visible start time')).toBeDisabled();
  const before = await state(page);
  await settings.getByLabel('Search timezones').fill('China');
  await settings.getByLabel('Timezone', { exact: true }).selectOption('Asia/Shanghai');
  await expect(calendar(page).getByRole('button', { name: 'Edit Weekly planning', exact: true })).toContainText('20:00');
  await expect(calendar(page).locator('[data-date="2026-09-15"]').getByRole('button', { name: 'Edit Portfolio deep work' })).toContainText('04:00');
  expect(await state(page)).toEqual(before);
  await page.screenshot({ path: 'test-results/settings.png' });
  await page.reload();
  await expect(calendar(page).getByRole('button', { name: 'Edit Weekly planning', exact: true })).toContainText('20:00');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('tab', { name: 'Calendar', exact: true }).click();
  await expect(settings.getByRole('switch')).toBeChecked();
  await settings.getByRole('switch').uncheck();
  await expect(calendar(page).locator('.time-axis span').first()).toHaveText('08:00');
});

test('navigation and shared completion work in every view', async ({ page }) => {
  const priority = page.getByRole('complementary', { name: 'Week context' }).getByRole('button', { name: 'Complete Project synthesis' });
  await priority.click();
  await expect(calendar(page).getByRole('button', { name: 'Edit Project synthesis' })).toHaveClass(/item-completed/);
  await page.getByRole('button', { name: 'Projects', exact: true }).click();
  const projects = page.getByRole('region', { name: 'Projects' });
  await expect(projects.getByRole('heading', { name: 'Projects', exact: true })).toBeVisible();
  await expect(projects.getByLabel('Complete Project synthesis')).toBeChecked();
  await projects.getByLabel('Complete Project synthesis').uncheck();
  await expect(projects.getByLabel('Complete Project synthesis')).not.toBeChecked();
  await page.getByRole('button', { name: 'Calendar', exact: true }).click();
  await page.getByRole('button', { name: 'Next week', exact: true }).click();
  await expect(calendar(page).locator('.timeline-day').first()).toHaveAttribute('data-date', '2026-09-21');
  await page.getByRole('button', { name: 'Next week', exact: true }).click();
  await expect(calendar(page).locator('.calendar-event')).toHaveCount(0);
  await page.getByRole('button', { name: 'Today', exact: true }).click();
  await expect(calendar(page).locator('.timeline-day').first()).toHaveAttribute('data-date', '2026-09-14');
  await page.getByRole('button', { name: 'Day', exact: true }).click();
  await expect(calendar(page).locator('.timeline-day')).toHaveCount(1);
  await page.getByRole('button', { name: 'Previous day', exact: true }).click();
  await expect(calendar(page).locator('.timeline-day')).toHaveAttribute('data-date', '2026-09-13');
  await page.getByRole('button', { name: 'Today', exact: true }).click();
  await page.getByRole('button', { name: 'Week', exact: true }).click();
  await expect(calendar(page).locator('.timeline-day')).toHaveCount(7);
});

test('edit, add, delete and next-day 1 AM window update canonical items and capacity', async ({ page }) => {
  const event = calendar(page).getByRole('button', { name: 'Edit Weekly planning', exact: true });
  const top = await event.evaluate(el => (el as HTMLElement).style.top);
  await event.click();
  let editor = page.getByRole('complementary', { name: 'Event editor' });
  await editor.getByLabel('Start time', { exact: true }).fill('09:00');
  await editor.getByLabel('End time', { exact: true }).fill('09:45');
  await editor.getByRole('button', { name: 'Save commitment' }).click();
  expect(await event.evaluate(el => (el as HTMLElement).style.top)).not.toBe(top);
  await quickAction(page, 'Add event');
  editor = page.getByRole('complementary', { name: 'Event editor' });
  await editor.getByLabel('Title', { exact: true }).fill('Late work test');
  await editor.getByLabel('Date', { exact: true }).fill('2026-09-15');
  await editor.getByLabel('Start time', { exact: true }).fill('00:15');
  await editor.getByLabel('End time', { exact: true }).fill('00:45');
  await editor.getByLabel('Estimated energy / effort').selectOption('High');
  await editor.getByRole('button', { name: 'Save commitment' }).click();
  await expect(calendar(page).locator('.day-heading').nth(1)).toContainText('/ 6h');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('tab', { name: 'Calendar', exact: true }).click();
  await page.getByLabel('Calendar visible start time').selectOption('8');
  await page.getByLabel('Calendar visible end time').selectOption('25');
  await expect(calendar(page).locator('[data-date="2026-09-14"]').getByRole('button', { name: 'Edit Late work test' })).toBeAttached();
  await page.getByRole('button', { name: 'Close settings' }).click();
  await calendar(page).getByRole('button', { name: 'Edit Late work test' }).click();
  await editor.getByRole('button', { name: 'Delete commitment' }).click();
  await editor.getByRole('button', { name: 'Confirm delete' }).click();
  expect((await state(page)).some((item: { title: string }) => item.title === 'Late work test')).toBe(false);
  await expect(calendar(page).locator('.day-heading').nth(1)).toContainText('/ 7.5h');
  await page.reload();
  await expect(calendar(page).getByRole('button', { name: 'Edit Weekly planning', exact: true })).toContainText('9:00 AM');
});

test('voice confirmation carries all edited fields, removal and timezone into apply; no early writes', async ({ page }) => {
  const before = await state(page);
  await voice(page);
  const panel = page.getByRole('complementary', { name: 'Voice confirmation' });
  await expect(panel.getByText('Thu, Sep 17', { exact: false })).toBeVisible();
  let interview = panel.getByRole('article', { name: 'Final Interview', exact: true });
  await interview.getByRole('button', { name: 'Edit', exact: true }).click();
  await interview.getByLabel('Title', { exact: true }).fill('Final panel interview');
  interview = panel.getByRole('article', { name: 'Final panel interview', exact: true });
  await interview.getByLabel('Date', { exact: true }).fill('2026-09-18');
  await interview.getByLabel('Start time', { exact: true }).fill('14:00');
  await interview.getByLabel('End time', { exact: true }).fill('15:30');
  await interview.getByLabel('Timezone', { exact: true }).selectOption('America/Los_Angeles');
  await interview.getByLabel('Course / Project').fill('Career');
  await interview.getByLabel('Priority', { exact: true }).selectOption('Medium');
  await interview.getByLabel('Flexibility', { exact: true }).selectOption('Flexible');
  await interview.getByLabel('Estimated energy / effort').selectOption('Low');
  await interview.getByLabel('Notes', { exact: true }).fill('Bring portfolio');
  await interview.getByRole('button', { name: 'Done editing' }).click();
  await panel.getByRole('article', { name: 'Online Assessment' }).getByRole('button', { name: 'Remove', exact: true }).click();
  await panel.getByRole('button', { name: 'Confirm & Replan' }).click();
  expect(await state(page)).toEqual(before);
  await page.getByRole('button', { name: 'Preview Changes' }).click();
  await expect(calendar(page).getByRole('button', { name: 'Edit Final panel interview' })).toContainText('5:00 PM');
  expect(await state(page)).toEqual(before);
  await page.screenshot({ path: 'test-results/confirmation-preview.png' });
  await page.getByRole('button', { name: 'Apply Changes' }).click();
  const after = await state(page);
  const saved = after.find((item: { title: string }) => item.title === 'Final panel interview');
  expect(saved).toMatchObject({ startsAt: '2026-09-18T21:00:00.000Z', endsAt: '2026-09-18T22:30:00.000Z', timezone: 'America/Los_Angeles', project: 'Career', priority: 'Medium', flexibility: 'Flexible', energy: 'Low', notes: 'Bring portfolio' });
  expect(after.some((item: { title: string }) => item.title === 'Online Assessment')).toBe(false);
  await expect(page.getByText('Your week has been updated.', { exact: true })).toBeVisible();
});

test('voice retry, validation, deadline edits and cancellation', async ({ page }) => {
  const before = await state(page);
  await voice(page);
  const panel = page.getByRole('complementary', { name: 'Voice confirmation' });
  await panel.getByRole('article', { name: 'Final Interview' }).getByRole('button', { name: 'Remove' }).click();
  await panel.getByRole('article', { name: 'Online Assessment' }).getByRole('button', { name: 'Remove' }).click();
  await expect(panel.getByRole('button', { name: 'Confirm & Replan' })).toBeDisabled();
  await panel.getByRole('button', { name: 'Retry voice' }).click();
  await expect(panel.getByRole('heading', { name: 'Here’s what I understood' })).toBeVisible();
  await expect(panel.getByRole('article')).toHaveCount(2);
  const interview = panel.getByRole('article', { name: 'Final Interview' });
  await interview.getByRole('button', { name: 'Edit', exact: true }).click();
  await interview.getByLabel('End time', { exact: true }).fill('01:00');
  await panel.getByRole('button', { name: 'Confirm & Replan' }).click();
  await expect(panel.getByRole('alert')).toContainText('End must be after start');
  await interview.getByLabel('End time', { exact: true }).fill('03:00');
  await interview.getByRole('button', { name: 'Done editing' }).click();
  const assessment = panel.getByRole('article', { name: 'Online Assessment' });
  await assessment.getByRole('button', { name: 'Edit', exact: true }).click();
  await assessment.getByLabel('Deadline date', { exact: true }).fill('2026-09-19');
  await assessment.getByLabel('Deadline time', { exact: true }).fill('22:30');
  await assessment.getByLabel('Timezone', { exact: true }).selectOption('Asia/Shanghai');
  await assessment.getByRole('button', { name: 'Done editing' }).click();
  await page.screenshot({ path: 'test-results/voice-confirmation.png' });
  await panel.getByRole('button', { name: 'Confirm & Replan' }).click();
  await page.getByRole('button', { name: 'Preview Changes' }).click();
  await expect(calendar(page).locator('.deadline-chip').filter({ hasText: 'Online Assessment' })).toContainText('10:30 AM');
  await page.getByRole('button', { name: 'Keep Current Plan' }).click();
  expect(await state(page)).toEqual(before);
});
