import { relationshipLabel } from '../hierarchy';
import { QuickAdd } from './QuickAdd';
import { useEventColors } from '../appearance';
import { Check, Circle, Flag, Gauge } from 'lucide-react';
import { capacities, dateInZone, displayDate, displayTime, itemsInWeek, type PlannerItem, type CalendarPreferences } from '../planner';

export function ContextPanel({ week, items, preferences: p, onToggle, onEdit, onAdd, onSpeak }: { onAdd: () => void; onSpeak: () => void; week: string; items: PlannerItem[]; preferences: CalendarPreferences; onToggle: (id: string) => void; onEdit: (item: PlannerItem) => void }) {
  const { projects, colorStyle, resolveColor } = useEventColors();
  const current = itemsInWeek(items, week, p.timezone);
  const priorities = current.filter(item => item.priority === 'High' || item.priority === 'Critical').slice(0, 3);
  const deadlines = current.filter(item => item.dueAt).sort((a, b) => a.dueAt!.localeCompare(b.dueAt!));
  const capacity = capacities(items, week, p.timezone);
  const booked = capacity.reduce((sum, day) => sum + day.bookedHours, 0);
  const available = capacity.reduce((sum, day) => sum + day.availableHours, 0);
  return <aside className="context-panel" aria-label="Week context"><QuickAdd onAdd={onAdd} onSpeak={onSpeak} /><div className="context-intro"><p className="eyebrow">Week at a glance</p><h2>Keep the important things visible.</h2></div>
    <section className="week-balance" aria-label="Week balance"><div className="week-balance-heading"><Gauge size={15} /><span>Week balance</span></div><div className="balance-track"><span style={{ width: `${available ? Math.min(100, booked / available * 100) : 0}%` }} /></div><p>{booked.toFixed(1)}h planned / {available}h capacity <strong>{Math.round(booked / available * 100)}%</strong></p>{capacity.some(day => day.bookedHours > day.availableHours) && <p className="capacity-warning">Some days exceed capacity</p>}</section>
    <section className="context-section"><div className="section-heading"><h3>Top priorities</h3><span>{priorities.length}</span></div><div className="priority-list">{priorities.map(item => <button data-color={resolveColor(item)} style={colorStyle(item)} className={`priority-row${item.completed ? ' completed' : ''}`} key={item.id} aria-label={`Complete ${item.title}`} aria-pressed={item.completed} onClick={() => onToggle(item.id)}><span className="priority-check">{item.completed ? <Check size={12} /> : <Circle size={15} />}</span><span className="priority-copy"><strong>{item.title}</strong><small>{relationshipLabel(item, projects)} · {displayDate(dateInZone(item.startsAt ?? item.dueAt!, p.timezone))}</small></span></button>)}{!priorities.length && <p className="section-note">No priorities this week.</p>}</div></section>
    <section className="context-section"><div className="section-heading"><h3>Upcoming deadlines</h3><Flag size={14} /></div><div className="deadline-list">{deadlines.map(item => <button data-color={resolveColor(item)} style={colorStyle(item)} className={`deadline-row contextual-deadline${item.completed ? ' item-completed' : ''}`} key={item.id} onClick={() => onEdit(item)}><div className="deadline-date"><strong>{Number(dateInZone(item.dueAt!, p.timezone).slice(-2))}</strong><span>{displayDate(dateInZone(item.dueAt!, p.timezone)).split(' ')[1]}</span></div><div className="deadline-copy"><strong>{item.title}</strong><small>{displayTime(item.dueAt!, p)} · {relationshipLabel(item, projects)}</small></div></button>)}{!deadlines.length && <p className="section-note">No deadlines this week.</p>}</div></section>
    <section className="context-section"><div className="section-heading"><h3>Daily capacity</h3><Gauge size={15} /></div><p className="section-note">Free time ≠ available capacity.</p><div className="capacity-list">{capacity.map(day => { const ratio = Math.round(day.bookedHours / day.availableHours * 100); return <div className={`capacity-row${day.bookedHours > day.availableHours ? ' over-capacity' : ''}`} key={day.day} title={`${day.bookedHours} effort hours / ${day.availableHours}h available`}><span>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][day.day]}</span><div className="capacity-meter"><span className={day.bookedHours > day.availableHours ? 'high' : 'low'} style={{ width: `${Math.min(100, ratio)}%` }} /></div><strong>{ratio}%{day.bookedHours > day.availableHours && <span aria-label="Over capacity"> !</span>}</strong></div>; })}</div><p className="section-note">High effort ×1.25 · low effort ×0.8. Late nights reduce available capacity. Personal and recovery time carry no productivity score.</p></section>

  </aside>;
}
